import type { Metadata } from "next";
import { Navbar } from "./components/Navbar";
import { ModelContextProvider } from "./context/ModelContext";

import "./globals.css";

export const metadata: Metadata = {
  title: "Look",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ModelContextProvider>
          <Navbar />
          {children}
        </ModelContextProvider>
      </body>
    </html>
  );
}
