import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* <section className={``}>
          <div className="w-full flex-1">{children}</div>
        </section> */}
        <div className="container mx-auto lg:w-2/3 w-screen">
          {/* <div className="p-4 bg-white w-3/12 h-screen sticky top-0">
            <h3 className="font-bold text-xl">IDENTIFY 🤖</h3>
          </div> */}
          {children}
        </div>
      </body>
    </html>
  );
}
